modLoader="javafml"
loaderVersion="[34,)"
authors="Tieso2001"
license="MIT License"

[[mods]]
modId="quenched"
version="${file.jarVersion}"
displayName="Quenched"
description='''
    Thirst mechanics'''

[[dependencies.quenched]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3]"
ordering="NONE"
side="BOTH"

[[dependencies.quenched]]
modId="forge"
mandatory=true
versionRange="[34,)"
ordering="NONE"
side="BOTH"